# Setup
title: xingchang's personal page
tagline: 
baseurl: ""
paginate: 1
locale: "en"

# About/contact
author:
  name: xingchang
  email: wangxingchang42@outlook.com
  url: "https://chang42.github.io/" 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown